providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r backend/requirements.txt"]

[start]
cmd = "cd backend && python main.py"
